name: Build and deployment
on:
  push:
    branches: [ "**" ]
jobs:
  build:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj --no-restore --verbosity normal
    - name: Pack
      if: github.ref == 'refs/heads/master'
      run: dotnet pack ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj --no-build --configuration Release
    - name: Publish
      if: github.ref == 'refs/heads/master'      
      run: dotnet nuget push "${{ github.event.repository.name }}/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
